// actions
// const INCREMENT = 'INCREMENT'
// const DECREMENT = 'DECREMENT'
// const RESET = 'RESET'

const FETCH_DATA = 'FETCH_DATA'
const API_ERROR = 'API_ERROR'
const FETCHED_DATA = 'FETCHED_DATA'
const FETCH_IMAGES = 'FETCH_IMAGES'
const FETCHED_IMAGES = 'FETCHED_IMAGES'
const IMAGE_API_ERROR = 'IMAGE_API_ERROR'

// action creators

export { FETCH_DATA, API_ERROR, FETCHED_DATA, FETCH_IMAGES, FETCHED_IMAGES, IMAGE_API_ERROR}